wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.13
    start_time: 1655892631
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 48
      - 51
      - 53
      - 55
      3:
      - 7
      4: 3.9.13
      5: 0.12.18
      8:
      - 1
      - 3
      - 5
alpha:
  desc: null
  value: 1.0
batch_size:
  desc: null
  value: 8
comments:
  desc: null
  value: 'Testing WandB '
compute_metric_every_n_epochs:
  desc: null
  value: 5
input_channels:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0005
max_overlap:
  desc: null
  value: 0.5
min_score:
  desc: null
  value: 0.5
n_classes:
  desc: null
  value: 2
scheduler:
  desc: null
  value: none
threshold:
  desc: null
  value: 0.5
top_k:
  desc: null
  value: 100
use_wandb:
  desc: null
  value: true
width_mult:
  desc: null
  value: 0.4
